name: Test UniCoil Anti-Recoil System

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: windows-latest
    
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10, 3.11]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        python test_deployment.py
    
    - name: Test imports
      run: |
        python -c "import tkinter, keyboard, mouse, psutil, json, threading, time; print('All imports successful')"
    
    - name: Test file structure
      run: |
        python -c "
        import os
        required_files = [
            'universal_antirecoil_app.py',
            'anti_recoil_app.py', 
            'enhanced_antirecoil_app.py',
            'launcher.py',
            'requirements.txt',
            'README.md',
            'LICENSE',
            '.gitignore'
        ]
        missing_files = [f for f in required_files if not os.path.exists(f)]
        if missing_files:
            print(f'Missing files: {missing_files}')
            exit(1)
        else:
            print('All required files present')
        " 